
'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Languages, ArrowRight, BookOpen } from "lucide-react";
import { useLanguage } from '@/hooks/use-language';

const languages = [
    { value: "english", label: "English" },
    { value: "hindi", label: "Hindi" },
    { value: "spanish", label: "Spanish" },
    { value: "french", label: "French" },
    { value: "german", label: "German" },
];

export default function GoLinguaPage() {
    const { t } = useLanguage();
    const [nativeLanguage, setNativeLanguage] = useState<string | null>(null);
    const [targetLanguage, setTargetLanguage] = useState<string | null>(null);

    return (
        <div className="max-w-4xl mx-auto space-y-8 p-4">
            <div className="text-center">
                <Languages className="mx-auto h-12 w-12 text-primary mb-4" />
                <h1 className="text-3xl md:text-4xl font-bold font-headline">GoLingua</h1>
                <p className="text-muted-foreground mt-2">Your AI-powered language learning partner.</p>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>Start a New Lesson</CardTitle>
                    <CardDescription>Select your native language and the language you want to learn.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                    <div className="grid grid-cols-1 md:grid-cols-3 items-center gap-4">
                        <div className="md:col-span-1">
                            <label className="text-sm font-medium">I speak...</label>
                            <Select onValueChange={setNativeLanguage}>
                                <SelectTrigger><SelectValue placeholder="Select Language" /></SelectTrigger>
                                <SelectContent>
                                    {languages.map(lang => (
                                        <SelectItem key={lang.value} value={lang.value}>{lang.label}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="flex justify-center">
                            <ArrowRight className="h-6 w-6 text-muted-foreground" />
                        </div>
                        <div className="md:col-span-1">
                             <label className="text-sm font-medium">I want to learn...</label>
                             <Select onValueChange={setTargetLanguage}>
                                <SelectTrigger><SelectValue placeholder="Select Language" /></SelectTrigger>
                                <SelectContent>
                                     {languages.map(lang => (
                                        <SelectItem key={lang.value} value={lang.value}>{lang.label}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                    </div>
                     <Button className="w-full" disabled={!nativeLanguage || !targetLanguage}>
                        <BookOpen className="mr-2 h-4 w-4" />
                        Start Learning
                    </Button>
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                    <CardTitle>How it works</CardTitle>
                </CardHeader>
                <CardContent>
                     <p>This is a placeholder for the GoLingua feature. When fully implemented, you will be able to select your languages and start an interactive, Duolingo-style lesson. The lessons will be generated by AI, adapting to your skill level and learning goals, and may include vocabulary, listening, and speaking exercises.</p>
                </CardContent>
            </Card>
        </div>
    )
}
